name: unet

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.9
  - chainer
  - cudnn
  - cupy
  - matplotlib
  - numpy<2.0
  - opencv
  - rasterio
  - requests
  - setuptools<68
  - tqdm
